### ISSUE TITLE
Force number of zones to 1

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cloud-processing#44]
As it it now, I get 3 x N nodes with `terraform apply` because it spreads the cluster by default to three zones, a, b and c.

Change the terraform script to give the expected number of nodes (or accept them being 3 x node count but take it into account in the job configuration)

**Comment by katilp** [comment]
Finally, it is enough to specify the zone in `region` in `terrafrom.tfvars`

Probably good to add this to README

**Comment by tomcordruw** [comment]
I think you mentioned in the last meeting that this behaviour was because you had specified a region instead of a zone?

I have added mention of this to the Readme files, but maybe to avoid confusion it would be better to also rename the `region`-variable to `zone` in terraform.vars (and the other files where it is referenced).
At least that's what I would suggest if it wouldn't cause any other issues.
